### PR TITLE
Creaking Heart generates at a 10% chance per tree.

### PR DESCRIPTION
**Pull request by Seigmannen**
This is my take on the creaking heart. I saw your changes to 5% just before i pushed this.

Anyway this one is at 10% change to generate creaking heart per tree.
It will randomly replace one pale oak log in the tree.
If the creaking heart has a log above and below, it will be active. If not it's inactive.

As you can see in the code i have commented out a part in the script that limits the creaking heart to only being able to generate in the pale garden biome. (Line 44-48). This was added because I like it like that.

Hope this script can be helpful in some ways.

### CODE REVIEW

**Comment by TreeOfSelf** [comment]
I like it, that's cool. Can you also update the [features.md](https://github.com/TreeOfSelf/CarpetSkyAdditions-Reborn/blob/main/docs/en_us/features.md) to describe the changes? Thanks.

**Comment by Seigmannen** [comment]
Sure. As soon as i'm able to.

Would that be with or without the pale garden criteria?

**Comment by TreeOfSelf** [comment]
I think with the pale garden criteria is a good idea, thank you.

**Comment by Seigmannen** [comment]
Now it's updated. Think the explanation is good enough now in feture.md from a players standpoint. The rest is basically vanilla features.

**Comment by TreeOfSelf** [comment]
Great, thanks.

**Pull request merged**
